from enum import Enum

class MetricType(str, Enum):
    RANK = "RANK"
    RATING = "RATING"
    PERFORMANCE_SCORE = "PERFORMANCE_SCORE"
    CONSISTENCY_SCORE = "CONSISTENCY_SCORE"
    ATTENDANCE_PERCENTAGE = "ATTENDANCE_PERCENTAGE"
    PROBLEM_SOLVED_COUNT = "PROBLEM_SOLVED_COUNT"

class ReportType(str, Enum):
    STUDENT = "STUDENT"
    TEACHER = "TEACHER"
    COHORT = "COHORT"
    PLATFORM = "PLATFORM"

class RiskReason(str, Enum):
    LOW_ATTENDANCE = "LOW_ATTENDANCE"
    DECLINING_PERFORMANCE = "DECLINING_PERFORMANCE"
    DECLINING_CONSISTENCY = "DECLINING_CONSISTENCY"