# Generated by Django 6.0.2 on 2026-07-05 17:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('STUDENT', 'STUDENT'), ('TEACHER', 'TEACHER'), ('ADMIN', 'ADMIN')], max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], max_length=10)),
                ('hashed_password', models.CharField(blank=True, max_length=255, null=True)),
                ('oauth_providers', models.JSONField(default=list)),
                ('must_change_password', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_user',
            },
        ),
    ]
