# Generated by Django 6.0.7 on 2026-08-25 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_djangootp'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='djangouser',
            index=models.Index(fields=['email'], name='idx_user_email'),
        ),
        migrations.AddIndex(
            model_name='djangouser',
            index=models.Index(fields=['role', 'status'], name='idx_user_role_status'),
        ),
    ]
