# Generated by Django 6.0.8 on 2026-08-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='codeforces_handle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
