# Generated by Django 6.0.6 on 2026-08-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_student_codeforces_handle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='attendance_percentage',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['cohort', 'status'], name='idx_student_cohort_status'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['cohort', 'attendance_percentage'], name='idx_student_cohort_attendance'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['cohort', 'year_phase', 'status'], name='idx_student_cohort_year_status'),
        ),
    ]
