# Generated by Django 6.0.8 on 2026-08-10 14:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherPaymentModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('teacher_id', models.UUIDField(db_index=True)),
                ('payment_month', models.CharField(max_length=7)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(default='ETB', max_length=10)),
                ('status', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('processed_by', models.UUIDField(blank=True, null=True)),
                ('processed_at', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'teacher_payment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentPaymentModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.UUIDField(db_index=True)),
                ('cohort_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('payment_month', models.CharField(max_length=7)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(default='ETB', max_length=10)),
                ('status', models.CharField(max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=200, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('verified_by', models.UUIDField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'student_payment',
                'ordering': ['-created_at'],
                'unique_together': {('student_id', 'payment_month')},
            },
        ),
    ]
