# Generated by Django 6.0.6 on 2026-08-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studentpaymentmodel',
            index=models.Index(fields=['student_id', '-created_at'], name='idx_student_payment_history'),
        ),
        migrations.AddIndex(
            model_name='studentpaymentmodel',
            index=models.Index(fields=['status', '-created_at'], name='idx_student_payment_status'),
        ),
        migrations.AddIndex(
            model_name='studentpaymentmodel',
            index=models.Index(fields=['status', 'due_date'], name='idx_student_payment_due'),
        ),
        migrations.AddIndex(
            model_name='studentpaymentmodel',
            index=models.Index(fields=['cohort_id', 'status'], name='idx_student_payment_cohort_status'),
        ),
        migrations.AddIndex(
            model_name='teacherpaymentmodel',
            index=models.Index(fields=['teacher_id', '-created_at'], name='idx_teacher_payment_history'),
        ),
        migrations.AddIndex(
            model_name='teacherpaymentmodel',
            index=models.Index(fields=['status', '-created_at'], name='idx_teacher_payment_status'),
        ),
        migrations.AddIndex(
            model_name='teacherpaymentmodel',
            index=models.Index(fields=['payment_month'], name='idx_teacher_payment_month'),
        ),
    ]
