# Generated by Django 6.0.7 on 2026-07-30 05:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsReportModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'analytics_report',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='CohortAnalyticsModel',
            fields=[
                ('cohort_id', models.UUIDField(primary_key=True, serialize=False)),
                ('cohort_name', models.CharField(max_length=200)),
                ('total_students', models.IntegerField(default=0)),
                ('average_performance_score', models.FloatField(default=0.0)),
                ('average_attendance_percentage', models.FloatField(default=0.0)),
                ('average_consistency_score', models.FloatField(default=0.0)),
                ('total_warnings_issued', models.IntegerField(default=0)),
                ('total_warnings_resolved', models.IntegerField(default=0)),
                ('active_warnings', models.IntegerField(default=0)),
                ('students_on_probation', models.IntegerField(default=0)),
                ('promoted_to_year2', models.IntegerField(default=0)),
                ('graduated', models.IntegerField(default=0)),
                ('dropped', models.IntegerField(default=0)),
                ('active_students', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cohort_analytics',
            },
        ),
        migrations.CreateModel(
            name='StudentAnalyticsModel',
            fields=[
                ('student_id', models.UUIDField(primary_key=True, serialize=False)),
                ('cohort_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('year_level', models.IntegerField(default=1)),
                ('rank', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
                ('performance_score', models.FloatField(default=0.0)),
                ('consistency_score', models.FloatField(default=0.0)),
                ('attendance_percentage', models.FloatField(default=0.0)),
                ('problem_solved_count', models.IntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('active_warning_count', models.IntegerField(default=0)),
                ('total_contests_participated', models.IntegerField(default=0)),
                ('average_contest_rank', models.FloatField(default=0.0)),
                ('best_contest_rank', models.IntegerField(default=0)),
                ('total_problems_in_contests', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'student_analytics',
            },
        ),
        migrations.CreateModel(
            name='HistoricalMetricModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.UUIDField(db_index=True)),
                ('snapshot_date', models.DateField(db_index=True)),
                ('rank', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
                ('performance_score', models.FloatField(default=0.0)),
                ('consistency_score', models.FloatField(default=0.0)),
                ('attendance_percentage', models.FloatField(default=0.0)),
                ('problem_solved_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'historical_metric',
                'ordering': ['snapshot_date'],
                'unique_together': {('student_id', 'snapshot_date')},
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntryModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.UUIDField(db_index=True)),
                ('student_name', models.CharField(max_length=200)),
                ('cohort_id', models.UUIDField(db_index=True)),
                ('cohort_name', models.CharField(max_length=200)),
                ('rank', models.IntegerField(db_index=True)),
                ('rating', models.FloatField(default=0.0)),
                ('performance_score', models.FloatField(default=0.0)),
                ('consistency_score', models.FloatField(default=0.0)),
                ('problem_solved_count', models.IntegerField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'leaderboard_entry',
                'ordering': ['rank'],
                'unique_together': {('student_id', 'cohort_id')},
            },
        ),
    ]
