# Generated by Django 6.0.8 on 2026-08-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='leaderboardentrymodel',
            index=models.Index(fields=['rank'], name='leaderboard_rank_9a8034_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboardentrymodel',
            index=models.Index(fields=['cohort_id', 'rank'], name='leaderboard_cohort__bc7a6a_idx'),
        ),
    ]
