# Generated by Django 6.0.7 on 2026-08-25 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_leaderboardentrymodel_leaderboard_rank_9a8034_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='leaderboardentrymodel',
            new_name='idx_leaderboard_rank',
            old_name='leaderboard_rank_9a8034_idx',
        ),
        migrations.RenameIndex(
            model_name='leaderboardentrymodel',
            new_name='idx_leaderboard_cohort_rank',
            old_name='leaderboard_cohort__bc7a6a_idx',
        ),
        migrations.AddIndex(
            model_name='cohortanalyticsmodel',
            index=models.Index(fields=['-average_performance_score'], name='idx_cohort_perf'),
        ),
        migrations.AddIndex(
            model_name='historicalmetricmodel',
            index=models.Index(fields=['student_id', 'snapshot_date'], name='idx_history_student_date'),
        ),
        migrations.AddIndex(
            model_name='historicalmetricmodel',
            index=models.Index(fields=['snapshot_date'], name='idx_history_date'),
        ),
        migrations.AddIndex(
            model_name='leaderboardentrymodel',
            index=models.Index(fields=['student_id'], name='idx_leaderboard_student'),
        ),
        migrations.AddIndex(
            model_name='studentanalyticsmodel',
            index=models.Index(fields=['cohort_id', '-performance_score'], name='idx_analytics_cohort_perf'),
        ),
        migrations.AddIndex(
            model_name='studentanalyticsmodel',
            index=models.Index(fields=['cohort_id', 'attendance_percentage'], name='idx_analytics_cohort_attendance'),
        ),
        migrations.AddIndex(
            model_name='studentanalyticsmodel',
            index=models.Index(fields=['rank'], name='idx_analytics_rank'),
        ),
        migrations.AddIndex(
            model_name='studentanalyticsmodel',
            index=models.Index(fields=['active_warning_count'], name='idx_analytics_warnings'),
        ),
    ]
