# Generated by Django 6.0.7 on 2026-08-25 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_leaderboard_rank_9a8034_idx_idx_leaderboard_rank_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='studentanalyticsmodel',
            new_name='idx_analytics_attendance',
            old_name='idx_analytics_cohort_attendance',
        ),
    ]
